version: 2
updates:
  # Angular (npm)
  - package-ecosystem: "npm"
    schedule:
      interval: "weekly"
    groups:
      angular:
        patterns:
          - "@angular/*"
          - "@angular-eslint/*"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"