name: Frontend validation

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22.x
          cache: "npm"
          cache-dependency-path: ./package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npx ng lint

      - name: Test
        run: npx ng test --watch=false

      - name: Build
        run: npx ng build --configuration production